name: Build
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * *" # daily at midnight

jobs:
  test:
    name: template setup test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup
        run: |
          git config user.name "Foo Bearer"
          bash "setup.bash" "asdf-foo" "http://example.org" "foo --help" "Foo Bearer" "asdf-community" "unlicense" "y"
      - name: Check setup result
        run: |
          set -xe
          ls -la .
          git log
          test ! -d template/
          grep "unlicense.org" LICENSE
          test "master" = "$(git rev-parse --abbrev-ref HEAD)"
          ! git grep -F -e "<YOUR TOOL>" \
                   --or -e "<TOOL HOMEPAGE>" \
                   --or -e "<TOOL CHECK>" \
                   --or -e "<YOUR NAME>" \
                   --or -e"<YOUR GITHUB USERNAME>"
